# Generated by Django 3.1.14 on 2022-06-28 16:33

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('msg', models.CharField(blank=True, max_length=200, null=True)),
                ('test', models.CharField(blank=True, max_length=200, null=True)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
