# Generated by Django 3.1.14 on 2022-06-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_obj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
