# Generated by Django 3.1.14 on 2022-06-29 18:40

from django.db import migrations
import djongo.models.fields
import test_obj.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_obj', '0002_auto_20220629_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEmbed',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('test_embed', djongo.models.fields.EmbeddedField(model_container=test_obj.models.TestAbs)),
            ],
        ),
    ]
