# Generated by Django 3.1.14 on 2022-06-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_obj', '0003_testembed'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testembed',
            table='TestEmbed',
        ),
    ]
